
export default function stringAvatar(name: string) {
  const splits = (name || "").trim().split(" ");
  return {
    children:
      splits.length > 1
        ? `${(splits[0][0] || "").toUpperCase()}${(
          splits[1][0] || ""
        ).toUpperCase()}`
        : `${(splits[0][0] || "").toUpperCase()}`,
  };
}


export const numberWithCommas = (number: any) => {
  return number ? number.toLocaleString('en-US') : 0; // 'en-IN' represents the locale for India, adjust as needed
};

export const getSymbol = (code:any): string => {
  switch (code) {
    case 'AED':
      return 'د.إ';
    case 'AFN':
      return '؋';
    case 'ALL':
      return 'L';
    case 'AMD':
      return '֏';
    case 'ANG':
      return 'ƒ';
    case 'AOA':
      return 'Kz';
    case 'ARS':
      return '$';
    case 'AUD':
      return 'A $';
    case 'AWG':
      return 'ƒ';
    case 'AZN':
      return '₼';
    case 'BAM':
      return 'KM';
    case 'BBD':
      return 'Bds$';
    case 'BDT':
      return '৳';
    case 'BGN':
      return 'лв';
    case 'BHD':
      return 'ب.د';
    case 'BIF':
      return 'FBu';
    case 'BMD':
      return '$';
    case 'BND':
      return 'B$';
    case 'BOB':
      return 'Bs.';
    case 'BRL':
      return 'R$';
    case 'BSD':
      return 'B$';
    case 'BTN':
      return 'Nu.';
    case 'BWP':
      return 'P';
    case 'BYN':
      return 'Br';
    case 'BZD':
      return 'BZ$';
    case 'CAD':
      return 'C $';
    case 'CDF':
      return 'FC';
    case 'CHF':
      return 'Fr.';
    case 'CLP':
      return '$';
    case 'CNY':
      return '元';
    case 'COP':
      return 'COL$';
    case 'CRC':
      return '₡';
    case 'CUP':
      return 'CUP';
    case 'CVE':
      return 'Esc';
    case 'CZK':
      return 'Kč';
    case 'DJF':
      return 'Fdj';
    case 'DKK':
      return 'kr';
    case 'DOP':
      return 'RD$';
    case 'DZD':
      return 'د.ج';
    case 'EGP':
      return 'E£';
    case 'ERN':
      return 'Nfa';
    case 'ETB':
      return 'Br';
    case 'EUR':
      return '€';
    case 'FJD':
      return 'FJ$';
    case 'FKP':
      return '£';
    case 'FOK':
      return 'kr';
    case 'GBP':
      return '£';
    case 'GEL':
      return '₾';
    case 'GGP':
      return '£';
    case 'GHS':
      return 'GH₵';
    case 'GIP':
      return '£';
    case 'GMD':
      return 'D';
    case 'GNF':
      return 'FG';
    case 'GTQ':
      return 'Q';
    case 'GYD':
      return 'G$';
    case 'HKD':
      return 'HK$';
    case 'HNL':
      return 'L';
    case 'HRK':
      return 'kn';
    case 'HTG':
      return 'G';
    case 'HUF':
      return 'Ft';
    case 'IDR':
      return 'Rp';
    case 'ILS':
      return '₪';
    case 'IMP':
      return '£';
    case 'INR':
      return '₹';
    case 'IQD':
      return 'ع.د';
    case 'IRR':
      return '﷼';
    case 'ISK':
      return 'kr';
    case 'JEP':
      return '£';
    case 'JMD':
      return 'J$';
    case 'JOD':
      return 'JD';
    case 'JPY':
      return '¥';
    case 'KES':
      return 'Ksh';
    case 'KGS':
      return 'с';
    case 'KHR':
      return '៛';
    case 'KID':
      return '$';
    case 'KRW':
      return '₩';
    case 'KWD':
      return 'KD';
    case 'KYD':
      return 'CI$';
    case 'KZT':
      return '₸';
    case 'LAK':
      return '₭';
    case 'LBP':
      return 'L£';
    case 'LKR':
      return 'Rs';
    case 'LRD':
      return 'L$';
    case 'LSL':
      return 'L';
    case 'LYD':
      return 'ل.د';
    case 'MAD':
      return 'د.م.';
    case 'MDL':
      return 'lei';
    case 'MGA':
      return 'Ar';
    case 'MKD':
      return 'ден';
    case 'MMK':
      return 'K';
    case 'MNT':
      return '₮';
    case 'MOP':
      return 'MOP$';
    case 'MRU':
      return 'UM';
    case 'MUR':
      return 'Rs';
    case 'MVR':
      return 'Rf';
    case 'MWK':
      return 'MK';
    case 'MXN':
      return 'Mex$';
    case 'MYR':
      return 'RM';
    case 'MZN':
      return 'MT';
    case 'NAD':
      return 'N$';
    case 'NGN':
      return '₦';
    case 'NIO':
      return 'C$';
    case 'NOK':
      return 'kr';
    case 'NPR':
      return 'Rs';
    case 'NZD':
      return 'NZ $';
    case 'OMR':
      return 'ر.ع.';
    case 'PAB':
      return 'B/.';
    case 'PEN':
      return 'S/.';
    case 'PGK':
      return 'K';
    case 'PHP':
      return '₱';
    case 'PKR':
      return 'Rs';
    case 'PLN':
      return 'zł';
    case 'PYG':
      return '₲';
    case 'QAR':
      return 'ر.ق';
    case 'RON':
      return 'lei';
    case 'RSD':
      return 'din.';
    case 'RUB':
      return '₽';
    case 'RWF':
      return 'RF';
    case 'SAR':
      return 'ر.س';
    case 'SBD':
      return 'SI$';
    case 'SCR':
      return 'SR';
    case 'SDG':
      return 'ج.س.';
    case 'SEK':
      return 'kr';
    case 'SGD':
      return 'S$';
    case 'SHP':
      return '£';
    case 'SLL':
      return 'Le';
    case 'SOS':
      return 'Sh';
    case 'SRD':
      return 'SRD';
    case 'SSP':
      return '£';
    case 'STN':
      return 'Db';
    case 'SVC':
      return '₡';
    case 'SYP':
      return '£';
    case 'SZL':
      return 'E';
    case 'THB':
      return '฿';
    case 'TJS':
      return 'ЅМ';
    case 'TMT':
      return 'm';
    case 'TND':
      return 'د.ت';
    case 'TOP':
      return 'T$';
    case 'TRY':
      return '₺';
    case 'TTD':
      return 'TT$';
    case 'TVD':
      return 'T$';
    case 'TWD':
      return 'NT$';
    case 'TZS':
      return 'TSh';
    case 'UAH':
      return '₴';
    case 'UGX':
      return 'USh';
    case 'USD':
      return 'US $';
    case 'UYU':
      return '$U';
    case 'UZS':
      return 'soʻm';
    case 'VES':
      return 'Bs.';
    case 'VND':
      return '₫';
    case 'VUV':
      return 'VT';
    case 'WST':
      return 'WS$';
    case 'XAF':
      return 'FCFA';
    case 'XCD':
      return 'EC$';
    case 'XDR':
      return 'SDR';
    case 'XOF':
      return 'CFA';
    case 'XPF':
      return '₣';
    case 'YER':
      return '﷼';
    case 'ZAR':
      return 'R';
    case 'ZMW':
      return 'ZK';
    case 'ZWL':
      return 'Z$';
    default:
      return code; // Return the code itself if no match is found
  }
};